apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/infs3208-431003/backend
        ports:
        - containerPort: 4000
        env: 
        - name: PORT
          value: "4000"
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "tailor"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "task_manager"
        - name: JWT_SECRET
          value: "your_jwt_secret_key"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.41.207.44
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: backend

