apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/infs3208-431003/backend
        ports:
        - containerPort: 4000
        livenessProbe:           # 添加 livenessProbe
          httpGet:
            path: /health        # backend 应暴露的健康检查路径
            port: 4000           # 使用后端的服务端口
          initialDelaySeconds: 10 # 容器启动后延迟多少秒进行健康检查
          periodSeconds: 10       # 每隔多少秒检查一次
        readinessProbe:          # 添加 readinessProbe
          httpGet:
            path: /ready         # backend 应暴露的就绪检查路径
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: backend

